#ifndef __SYSCALL_LIST_H__
#define __SYSCALL_LIST_H__

#ifndef SYSCALL
#define SYSCALL(name, num)
#endif

SYSCALL(SYS_CREATE, 1)
SYSCALL(SYS_MYTID, 2)
SYSCALL(SYS_MYPARENTTID, 3)
SYSCALL(SYS_YIELD, 4)
SYSCALL(SYS_EXIT, 5)
SYSCALL(SYS_SEND, 6)
SYSCALL(SYS_RECEIVE, 7)
SYSCALL(SYS_REPLY, 8)
SYSCALL(SYS_KLOG, 9)
SYSCALL(SYS_PANIC, 10)
SYSCALL(SYS_WAIT_TID, 11)
SYSCALL(SYS_AWAIT_EVENT, 12)
SYSCALL(SYS_SETUP_IDLE_TASK, 13)
SYSCALL(SYS_GET_UNREAD_KLOGS, 14)
SYSCALL(SYS_GET_TASK_INFO, 15)
SYSCALL(SYS_RECEIVE_NONBLOCK, 16)
SYSCALL(SYS_REBOOT, 17)
SYSCALL(SYS_KILL, 18)
SYSCALL(SYS_TOGGLE_IDLE_DISPLAY, 19)

#endif
