#ifndef MARKLIN_ERROR_H
#define MARKLIN_ERROR_H

#include "types.h"

typedef enum {
	MARKLIN_ERROR_OK = 0,
	MARKLIN_ERROR_NOT_FOUND = -1,
	MARKLIN_ERROR_INVALID_ARGUMENT = -2,
	MARKLIN_ERROR_COMMUNICATION = -3,
	MARKLIN_ERROR_QUEUE_FULL = -4,
	MARKLIN_ERROR_TIMEOUT = -5,
	MARKLIN_ERROR_UNKNOWN = -6,
	MARKLIN_ERROR_NOT_INITIALIZED = -7,
	MARKLIN_ERROR_NO_PATH = -8,
	MARKLIN_ERROR_PENDING = -9,
	MARKLIN_ERROR_ALREADY_RESERVED = -10,
	MARKLIN_ERROR_NOT_OWNER = -11,
} marklin_error_t;

#endif /* MARKLIN_ERROR_H */
