#ifndef __REVERSAL_BLACKLIST_H__
#define __REVERSAL_BLACKLIST_H__

#ifndef REVERSAL_BLACKLIST_NODE
#define REVERSAL_BLACKLIST_NODE(name)

REVERSAL_BLACKLIST_NODE(B7)
REVERSAL_BLACKLIST_NODE(B8)
REVERSAL_BLACKLIST_NODE(B11)
REVERSAL_BLACKLIST_NODE(B9)
REVERSAL_BLACKLIST_NODE(B10)
REVERSAL_BLACKLIST_NODE(A11)
REVERSAL_BLACKLIST_NODE(A12)
REVERSAL_BLACKLIST_NODE(A15)
REVERSAL_BLACKLIST_NODE(A16)
REVERSAL_BLACKLIST_NODE(EN3)
REVERSAL_BLACKLIST_NODE(EN4)
REVERSAL_BLACKLIST_NODE(EN5)
REVERSAL_BLACKLIST_NODE(EN7)
REVERSAL_BLACKLIST_NODE(EN9)
REVERSAL_BLACKLIST_NODE(EN10)
REVERSAL_BLACKLIST_NODE(EN6)
REVERSAL_BLACKLIST_NODE(EN8)
REVERSAL_BLACKLIST_NODE(EX3)
REVERSAL_BLACKLIST_NODE(EX4)
REVERSAL_BLACKLIST_NODE(EX5)
REVERSAL_BLACKLIST_NODE(EX7)
REVERSAL_BLACKLIST_NODE(EX9)
REVERSAL_BLACKLIST_NODE(EX10)
REVERSAL_BLACKLIST_NODE(EX6)
REVERSAL_BLACKLIST_NODE(EX8)

#endif

#endif
