#ifndef __MARKLIN_BLACKLISTED_SENSORS_LIST_H__
#define __MARKLIN_BLACKLISTED_SENSORS_LIST_H__

#ifndef BROKEN_SENSOR
#define BROKEN_SENSOR(track, sensor_name)
#endif

// Track A
BROKEN_SENSOR(MARKLIN_TRACK_TYPE_A, "B10")
BROKEN_SENSOR(MARKLIN_TRACK_TYPE_A, "B9")
BROKEN_SENSOR(MARKLIN_TRACK_TYPE_A, "C2")

// Track B
BROKEN_SENSOR(MARKLIN_TRACK_TYPE_B, "C12")

#endif /* __MARKLIN_BLACKLISTED_SENSORS_LIST_H__ */
